export const SITE_LANGUAGES = ['ar', 'en', 'fr'] as const;
export type SiteLanguage = (typeof SITE_LANGUAGES)[number];
export const SITE_LANGUAGE_COOKIE = 'dr-hossam-site-language';
export const DEFAULT_SITE_LANGUAGE: SiteLanguage = 'ar';
export function isSiteLanguage(value:string|null|undefined):value is SiteLanguage{return value==='ar'||value==='en'||value==='fr';}
export function normalizeSiteLanguage(value:string|null|undefined):SiteLanguage{return isSiteLanguage(value)?value:DEFAULT_SITE_LANGUAGE;}
export const siteCopy={
 ar:{home:'الرئيسية',courts:'أماكن العمل',lawyers:'زملاء العمل',calendar:'التقويم',search:'البحث',quick:'تنقّل سريع',clients:'العملاء',assign:'تكليف',addLawyer:'إضافة محامي',addLocation:'إضافة مكان عمل',cases:'ملفات القضايا',personalAssign:'تكليف شخصي',allCourts:'عرض كل أماكن العمل',allLawyers:'عرض كل زملاء العمل',otherLocations:'أماكن العمل الأخرى',login:'تسجيل دخول',logout:'تسجيل الخروج',admin:'الإدارة',archive:'الأرشيف',searchPlaceholder:'ابحث عن عميل، قضية، مكان، محامٍ…',searchShort:'ابحث...',menu:'القائمة',officeFeed:'فيد المكتب',posts:'منشور',noPosts:'لا توجد منشورات حالياً',noPostsHint:'ستظهر هنا مهام المحامين والجلسات والنشاط الإداري لحظة إضافتها.',stats:['جلسات اليوم','جلسات الغد','جلسات حرجة','مهام مفتوحة','زملاء العمل','المواعيد القادمة'],databaseUnavailable:'قاعدة البيانات غير متاحة حالياً.',diagnostics:'عرض تشخيص الخدمة',offices:'عناوين المكاتب',contact:'بيانات التواصل',mainOffice:'المقر الرئيسي',cairoOffice:'مكتب القاهرة',gizaOffice:'مكتب الجيزة',phones:'تليفونات',fax:'تليفون / فاكس',mobile:'محمول المكتب'},
 en:{home:'Home',courts:'Work Locations',lawyers:'Colleagues',calendar:'Calendar',search:'Search',quick:'Quick navigation',clients:'Clients',assign:'Assign task',addLawyer:'Add lawyer',addLocation:'Add work location',cases:'Case files',personalAssign:'Personal task',allCourts:'View all work locations',allLawyers:'View all colleagues',otherLocations:'Other work locations',login:'Sign in',logout:'Sign out',admin:'Administration',archive:'Archive',searchPlaceholder:'Search for a client, case, location, or colleague…',searchShort:'Search…',menu:'Menu',officeFeed:'Office feed',posts:'posts',noPosts:'No posts yet',noPostsHint:'Lawyer tasks, hearings, and office activity will appear here as they are added.',stats:["Today's hearings","Tomorrow's hearings",'Critical hearings','Open tasks','Colleagues','Upcoming appointments'],databaseUnavailable:'The database is currently unavailable.',diagnostics:'View service diagnostics',offices:'Office addresses',contact:'Contact details',mainOffice:'Main office',cairoOffice:'Cairo office',gizaOffice:'Giza office',phones:'Phones',fax:'Phone / Fax',mobile:'Office mobile'},
 fr:{home:'Accueil',courts:'Lieux de travail',lawyers:'Collègues',calendar:'Calendrier',search:'Recherche',quick:'Navigation rapide',clients:'Clients',assign:'Attribuer une tâche',addLawyer:'Ajouter un avocat',addLocation:'Ajouter un lieu de travail',cases:'Dossiers',personalAssign:'Tâche personnelle',allCourts:'Voir tous les lieux de travail',allLawyers:'Voir tous les collègues',otherLocations:'Autres lieux de travail',login:'Connexion',logout:'Déconnexion',admin:'Administration',archive:'Archives',searchPlaceholder:'Rechercher un client, dossier, lieu ou collègue…',searchShort:'Rechercher…',menu:'Menu',officeFeed:'Fil du cabinet',posts:'publications',noPosts:'Aucune publication pour le moment',noPostsHint:'Les tâches, audiences et activités apparaîtront ici.',stats:['Audiences du jour','Audiences de demain','Audiences critiques','Tâches ouvertes','Collègues','Rendez-vous à venir'],databaseUnavailable:'La base de données est actuellement indisponible.',diagnostics:'Voir le diagnostic du service',offices:'Adresses des bureaux',contact:'Coordonnées',mainOffice:'Bureau principal',cairoOffice:'Bureau du Caire',gizaOffice:'Bureau de Gizeh',phones:'Téléphones',fax:'Téléphone / Fax',mobile:'Mobile du cabinet'}
} as const;
export function copyFor(language:SiteLanguage){return siteCopy[language];}
