import { NextResponse } from 'next/server';
import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { logActivity } from '@/lib/activity';
import { notifyTaskAssigned } from '@/lib/notifications';
import { user } from '@/lib/api';
import { createOfficeRequest, isSeniorManagement, notifySenior, officeId } from '@/lib/office-workflow';
const bodySchema=z.object({message:z.string().trim().min(1).max(4000),confirm:z.boolean().optional(),action:z.record(z.string(),z.unknown()).optional()});
const MODEL='gemini-2.5-flash';
function event(x:unknown){return `data: ${JSON.stringify(x)}\n\n`;}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
async function context(){const [tasks,cases,lawyers,locations,clients]=await Promise.all([prisma.task.findMany({where:{status:{notIn:['COMPLETED','CANCELLED']}},orderBy:{scheduledDate:'asc'},take:60,include:{location:{select:{name:true}},caseRecord:{select:{name:true,number:true,clientName:true}},assignees:{select:{lawyer:{select:{fullName:true}}}}}}),prisma.caseRecord.findMany({take:100,select:{id:true,name:true,number:true,clientName:true}}),prisma.lawyer.findMany({where:{active:true},take:100,select:{id:true,fullName:true}}),prisma.location.findMany({take:250,select:{id:true,name:true,nameEn:true}}),prisma.$queryRawUnsafe<any[]>(`SELECT "id","name","phone","email","status" FROM "clients" WHERE COALESCE("status",'MAIN') NOT IN ('REJECTED','DELETED') ORDER BY "name" LIMIT 200`)]);return{tasks:tasks.map(t=>({id:t.id,description:t.description,date:t.scheduledDate?.toISOString().slice(0,10)||null,time:t.scheduledTime,location:t.location?.name||null,case:t.caseRecord?.name||null,caseNumber:t.caseRecord?.number||null,client:t.caseRecord?.clientName||null,lawyers:t.assignees.map(a=>a.lawyer.fullName)})),cases,lawyers,locations,clients};}
function localAnswer(message:string,c:any): string | null {
  const raw=message.trim();
  const q=raw.toLocaleLowerCase('ar-EG');
  const normalize=(v:string)=>v.toLocaleLowerCase('ar-EG').replace(/[\u064B-\u065F]/g,'').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي');
  const nq=normalize(q);
  const has=(...words:string[])=>words.some(w=>nq.includes(normalize(w)));
  const list=(items:any[],key:string)=>items.slice(0,12).map(x=>String(x?.[key]??'')).filter(Boolean).join('، ');
  if(has('عدد العملاء','عدد العميل','كم عميل','clients')) return `عدد العملاء المسجلين: ${c.clients.length}.`;
  if(has('المحامين','المحاميين','المحامين الموجودين','lawyers')) return c.lawyers.length ? `المحامون: ${list(c.lawyers,'fullName')}.` : 'لا توجد بيانات لمحامين نشطين حاليًا.';
  if(has('القضايا','القضيه','القضايا الحالية','cases')) return c.cases.length ? `القضايا المسجلة: ${c.cases.slice(0,12).map((x:any)=>`${x.name}${x.number?' — '+x.number:''}${x.clientName?' — '+x.clientName:''}`).join('؛ ')}.` : 'لا توجد قضايا مسجلة في البيانات الحالية.';
  if(has('المهام','التكليفات','المهام القادمة','tasks')) return c.tasks.length ? `المهام القادمة: ${c.tasks.slice(0,10).map((x:any)=>`${x.description}${x.date?' — '+x.date:''}${x.time?' — '+x.time:''}`).join('؛ ')}.` : 'لا توجد مهام مفتوحة مسجلة حاليًا.';
  if(has('المواقع','المحاكم','الاماكن','locations')) return c.locations.length ? `الأماكن المسجلة: ${list(c.locations,'name')}.` : 'لا توجد أماكن مسجلة حاليًا.';
  const lawyer=c.lawyers.find((x:any)=>typeof x?.fullName==='string' && normalize(x.fullName)===nq);
  if(lawyer)return `المحامي: ${lawyer.fullName}.`;
  const location=c.locations.find((x:any)=>[x?.name,x?.nameEn].some((v:any)=>typeof v==='string'&&normalize(v).includes(nq)));
  if(location)return `المكان: ${location.name}${location.nameEn?' — '+location.nameEn:''}.`;
  const kase=c.cases.find((x:any)=>[x?.name,x?.number,x?.clientName].some((v:any)=>typeof v==='string'&&normalize(v).includes(nq)));
  if(kase)return `القضية: ${kase.name}${kase.number?' — رقم '+kase.number:''}${kase.clientName?' — العميل: '+kase.clientName:''}.`;
  const task=c.tasks.find((x:any)=>[x?.description,x?.location,x?.case,x?.caseNumber,x?.client].some((v:any)=>typeof v==='string'&&normalize(v).includes(nq)));
  if(task)return `المهمة: ${task.description}${task.date?' — '+task.date:''}${task.time?' — '+task.time:''}${task.location?' — '+task.location:''}.`;
  if(has('صباح الخير','مساء الخير','مرحبا','اهلا','hello','hi','bonjour')) return 'مرحبًا. يمكنني مساعدتك في البحث داخل بيانات المكتب عن العملاء والقضايا والمحامين والمهام والمواقع.';
  return null;
}
async function geminiStream(message:string,c:any,signal?:AbortSignal){const key=process.env.GEMINI_API_KEY;if(!key)throw new Error('GEMINI_API_KEY_MISSING');const system=`أنت مساعد ذكي لمكتب Loutfi Law Firm. افهم العربية المصرية والفصحى والإنجليزية والفرنسية والأخطاء الإملائية. أجب مباشرة وباختصار مفيد، بدون Markdown ثقيل أو reasoning داخلي. يجوز لك الإجابة عن الأسئلة العامة أيضًا. عند السؤال عن بيانات المكتب، استخدم البيانات الحالية المرفقة ولا تخترع أسماء أو أرقامًا أو مواعيد. إذا لم توجد المعلومة في بيانات المكتب فقل إنها غير موجودة، ثم أجب على الجزء العام إن أمكن.\nبيانات المكتب: ${JSON.stringify(c)}`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:streamGenerateContent?alt=sse`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:message}]}],generationConfig:{temperature:.4,maxOutputTokens:4096}}),signal,cache:'no-store'});if(!r.ok){const detail=await r.text().catch(()=> '');throw new Error(`GEMINI_${r.status}:${detail.slice(0,400)}`)}if(!r.body)throw new Error('GEMINI_NO_STREAM');return r.body;}
async function executeAction(session:any,a:any){const senior=await isSeniorManagement(session);if(!senior&&session.role==='lawyer'){const rid=await createOfficeRequest({type:a.type==='create_session'?'TASK_CREATE_SESSION':'TASK_CREATE',title:a.type==='create_session'?'طلب إضافة جلسة':'طلب إضافة تكليف',reason:String(a.description||''),payload:a,targetEntityType:'task',session});await notifySenior('طلب تنفيذ جديد',String(a.description||'طلب جديد'),'/admin/office').catch(()=>undefined);return{ok:true,requiresApproval:true,requestId:rid,reply:'تم إرسال الطلب للإدارة العليا للموافقة.'};}const description=String(a.description||'مهمة جديدة').trim();const locationId=a.locationId?String(a.locationId):null;const date=a.scheduledDate?String(a.scheduledDate):null;const time=a.scheduledTime?String(a.scheduledTime):null;const lawyerIds=Array.isArray(a.lawyerIds)?a.lawyerIds.map(String):[];if(a.type==='create_session'&&(!locationId||!date||!time||!lawyerIds.length))return{error:'بيانات الجلسة ناقصة'};const id=officeId('task');if(!locationId)return{error:'مكان العمل مطلوب'};await prisma.$executeRawUnsafe(`INSERT INTO "tasks" ("id","locationId","description","notes","scheduledDate","scheduledTime","status","createdById","authorId","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5::date,$6,'PENDING',$7,$8,NOW(),NOW())`,id,locationId,description,a.notes?String(a.notes):null,date,time,session.role==='admin'?session.userId:null,session.role==='lawyer'?session.lawyerId:null);for(const lid of lawyerIds)await prisma.$executeRawUnsafe(`INSERT INTO "task_assignments" ("id","taskId","lawyerId","createdAt") VALUES ($1,$2,$3,NOW()) ON CONFLICT ("taskId","lawyerId") DO NOTHING`,officeId('assign'),id,lid);await logActivity({action:'CREATED',summary:`أنشأ ${a.type==='create_session'?'جلسة':'مهمة'}: ${description}`,taskId:id,locationId,byUserId:session.role==='admin'?session.userId:undefined,byLawyerId:session.role==='lawyer'?session.lawyerId:undefined}).catch(()=>undefined);if(lawyerIds.length)await notifyTaskAssigned(lawyerIds,description,date?(date+(time?` — ${time}`:'')):'بالتنسيق',`/sessions/${id}`).catch(()=>undefined);return{ok:true,success:true,reply:a.type==='create_session'?'تمت إضافة الجلسة بنجاح.':'تم إنشاء المهمة بنجاح.',navigation:{path:`/sessions/${id}`,label:a.type==='create_session'?'فتح الجلسة':'فتح المهمة'}};}
export async function GET(){const session=await user();if(!session)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});return NextResponse.json({configured:Boolean(process.env.GEMINI_API_KEY),model:MODEL});}
export async function POST(req:Request){const session=await user();if(!session)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});let body;try{body=bodySchema.parse(await req.json())}catch{return NextResponse.json({error:'طلب غير صالح'},{status:400})}const c=await context();if(body.confirm&&body.action){const result=await executeAction(session,body.action);if(result.error)return NextResponse.json({ok:false,error:result.error,action:body.action});return NextResponse.json(result);}const local=localAnswer(body.message,c);if(local)return NextResponse.json({reply:local,provider:'local',configured:Boolean(process.env.GEMINI_API_KEY)});try{const upstream=await geminiStream(body.message,c,AbortSignal.timeout(45000));const reader=upstream.getReader();const decoder=new TextDecoder();const encoder=new TextEncoder();let buffer='';return new Response(new ReadableStream({async start(controller){try{for(;;){const{value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split(/\n\n/);buffer=blocks.pop()||'';for(const block of blocks){for(const line of block.split('\n')){if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(!raw||raw==='[DONE]')continue;try{const j=JSON.parse(raw);const text=j.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('')||'';if(text)controller.enqueue(encoder.encode(event({type:'token',text})));}catch{}}}}controller.enqueue(encoder.encode(event({type:'done',configured:true})));controller.close();}catch(e){console.error('[assistant]',e);controller.enqueue(encoder.encode(event({type:'error',error:'تعذر الاتصال بموديل Gemini حالياً.'})));controller.close();}}}),{headers:{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-transform','X-Accel-Buffering':'no'}});}catch(e){console.error('[assistant]',e);return NextResponse.json({reply:localAnswer(body.message,c) || 'لم أجد هذه المعلومة في بيانات المكتب الحالية. يمكنك البحث باسم العميل أو القضية أو المحامي أو المهمة.',provider:'local-fallback',configured:Boolean(process.env.GEMINI_API_KEY)},{status:200});}}
