import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { handle, json, readJson, requireStaff } from '@/lib/api';
const bodySchema=z.object({message:z.string().trim().min(1).max(4000),confirm:z.boolean().optional(),action:z.record(z.string(),z.unknown()).optional()});
const OPENROUTER_URL='https://openrouter.ai/api/v1/chat/completions';
const normalize=(s:string)=>s.normalize('NFKC').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ـ/g,'').replace(/\s+/g,' ').trim().toLowerCase();
const nav=(path:string,label:string)=>({path,label});
async function context(){const now=new Date();const [tasks,cases,lawyers,locations]=await Promise.all([prisma.task.findMany({where:{status:{notIn:['COMPLETED','CANCELLED']},OR:[{scheduledDate:{gte:now}},{scheduledDate:null}]},orderBy:{scheduledDate:'asc'},take:30,include:{location:{select:{name:true,slug:true}},assignees:{select:{lawyer:{select:{fullName:true}}}}}}),prisma.caseRecord.findMany({orderBy:{id:'desc'},take:50,select:{id:true,name:true,number:true,clientName:true}}).catch(()=>[]),prisma.lawyer.findMany({where:{active:true},orderBy:{fullName:'asc'},take:100,select:{id:true,fullName:true,slug:true}}),prisma.location.findMany({orderBy:{name:'asc'},take:300,select:{id:true,name:true,slug:true,type:true}})]);return {tasks:tasks.map(t=>({id:t.id,description:t.description,date:t.scheduledDate?.toISOString().slice(0,10)??null,time:t.scheduledTime,location:t.location?.name??null,lawyers:t.assignees.map(a=>a.lawyer.fullName)})),cases,lawyers,locations};}
function deterministic(message:string,c:any){const n=normalize(message);if(/(اقدم|تقديم|تدريب|متدرب|ازاي استخدم|كيف استخدم|اعمل ايه|ابدأ)/.test(n))return {reply:'هذا النظام مخصص لإدارة المكتب داخليًا. إذا كنت تقصد كيفية استخدام وظيفة داخل النظام، يمكنني إرشادك مباشرة أو نقلك إلى دليل الاستخدام.',navigation:nav('/admin/guide','الانتقال إلى دليل الاستخدام')};if(/(مواعيد|جلسات|اليوم|بكره|غدا)/.test(n))return {reply:`يمكنني عرض المواعيد والمهام الفعلية من النظام. يوجد حاليًا ${c.tasks.length} مهمة/جلسة مفتوحة في البيانات المتاحة.`,navigation:nav('/calendar','الانتقال إلى التقويم')};if(/(قضايا|قضاي|case)/.test(n))return {reply:`بيانات القضايا متاحة داخل النظام. يوجد ${c.cases.length} سجلًا ضمن البيانات الحالية.`,navigation:nav('/admin?tab=cases','الانتقال إلى القضايا')};return {reply:'أفهم العربية المصرية والأخطاء الإملائية الشائعة. اكتب المطلوب بصياغتك الطبيعية، مثل: «أقدم إزاي؟» أو «عايز أعرف جلسات بكرة»، وسأتعامل معه وفق بيانات النظام الفعلية.'};}
function extractJson(text:string){try{return JSON.parse(text)}catch{const m=text.match(/\{[\s\S]*\}/);if(m)try{return JSON.parse(m[0])}catch{}return null}}
async function ai(message:string,c:any){const dbKey=await prisma.adminSetting.findUnique({where:{key:'assistant_api_key'}}).then(x=>x?.value||'').catch(()=> '');const key=process.env.OPENROUTER_API_KEY||dbKey;if(!key)return deterministic(message,c);const model=process.env.OPENROUTER_MODEL||'openrouter/free';const system=`أنت مساعد تشغيلي داخلي رسمي لمكتب الدكتور حسام لطفي للمحاماة. افهم الفصحى والعربية المصرية والإنجليزية والفرنسية، ولا تعتمد على كلمات مفتاحية حرفية. افهم الاختلافات الإملائية والكتابية مثل: اقدم/أقدم، ازاي/إزاي، عايز/عايز، مواعيد/ميعاد، بكرة/بكره، جلسة/جلسه، قضية/قضيه. استنتج نية المستخدم من المعنى الكامل. لا تخترع بيانات. عند سؤال عن وظيفة أو صفحة في النظام أرجع navigation برابط مباشر إن كان معروفًا. عند طلب تغيير بيانات أرجع action مقترحًا ولا تنفذه بنفسك. أعد JSON فقط بالشكل: {reply:string,navigation?:{path:string,label:string},action?:{type:string,description:string,scheduledDate?:string,scheduledTime?:string,lawyerIds?:string[],locationId?:string}}. بيانات النظام الحالية: ${JSON.stringify(c)}`;const r=await fetch(OPENROUTER_URL,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','HTTP-Referer':process.env.NEXT_PUBLIC_APP_URL||'https://dr-hossam-lotfy-hw88.vercel.app','X-Title':'Dr Hossam Lotfy Office Assistant'},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:message}],temperature:0.1,response_format:{type:'json_object'}})});if(!r.ok)throw new Error(`AI provider ${r.status}`);const d=await r.json();const out=extractJson(d.choices?.[0]?.message?.content||'');return out||deterministic(message,c)}
export const POST=handle(async(req:Request)=>{const session=await requireStaff();const data=await readJson(req as never,bodySchema);const c=await context();if(data.confirm&&data.action?.type==='create_task'){const a=data.action;const description=String(a.description||'').trim();if(!description)return json({error:'وصف المهمة مطلوب'},{status:400});const date=typeof a.scheduledDate==='string'?a.scheduledDate:undefined;const time=typeof a.scheduledTime==='string'?a.scheduledTime:undefined;const lawyerIds=Array.isArray(a.lawyerIds)?a.lawyerIds.filter((x):x is string=>typeof x==='string'):[];const created=await prisma.task.create({data:{description,scheduledDate:date?new Date(`${date}T00:00:00`):undefined,scheduledTime:time,createdById:session.userId,assignees:{create:lawyerIds.map(id=>({lawyer:{connect:{id}}}))}}});return json({ok:true,reply:'تم تنفيذ الإجراء بنجاح.',success:true,action:{type:'create_task',id:created.id},navigation:nav(`/sessions/${created.id}`,'فتح المهمة')});}try{return json(await ai(data.message,c))}catch(error){console.error('[assistant]',error);return json({...deterministic(data.message,c),providerError:true})}});
export const GET=handle(async()=>{await requireStaff();const db=await prisma.adminSetting.findUnique({where:{key:'assistant_api_key'}}).catch(()=>null);return json({configured:Boolean(process.env.OPENROUTER_API_KEY||db?.value),source:process.env.OPENROUTER_API_KEY?'environment':db?.value?'admin':'none',model:process.env.OPENROUTER_MODEL||'openrouter/free'});});
