import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { handle, json, readJson, user } from '@/lib/api';
import { logActivity } from '@/lib/activity';
import { notifyTaskAssigned } from '@/lib/notifications';

type SessionLike = {role:'admin'|'lawyer';userId?:string;lawyerId?:string;name:string;userRole?:string;isAdmin?:boolean};
type Choice={id:string;name:string};
type Action={type:string;description?:string;scheduledDate?:string;scheduledTime?:string;lawyerIds?:string[];lawyerNames?:string[];locationId?:string;locationName?:string;caseName?:string;caseNumber?:string;clientName?:string;notes?:string;taskId?:string;status?:string;missing?:string[];choices?:{lawyers?:Choice[];locations?:Choice[]}};
const bodySchema=z.object({message:z.string().trim().min(1).max(4000),confirm:z.boolean().optional(),action:z.record(z.string(),z.unknown()).optional()});
const OPENROUTER_URL='https://openrouter.ai/api/v1/chat/completions';
const normalize=(s:string)=>s.normalize('NFKC').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[\u064B-\u065F\u0670]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ـ/g,'').replace(/\s+/g,' ').trim().toLowerCase();
const nav=(path:string,label:string)=>({path,label});
const parseDigits=(s:string)=>s.replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)));
function cairoToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function shiftDate(days:number){const d=new Date(`${cairoToday()}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function nextWeekday(text:string){const n=normalize(text);const map:[string,number][]=[['الاحد',0],['الاتنين',1],['الاثنين',1],['الثلاثاء',2],['الاربعاء',3],['الخميس',4],['الجمعه',5],['الجمعة',5],['السبت',6]];for(const [name,target] of map){if(n.includes(name)){const today=new Date(`${cairoToday()}T12:00:00Z`);const cur=today.getUTCDay();let diff=(target-cur+7)%7;if(diff===0)diff=7;return shiftDate(diff)}}return undefined;}
function extractDate(text:string){const n=normalize(parseDigits(text));const iso=n.match(/\b(20\d{2})[-\/.](\d{1,2})[-\/.](\d{1,2})\b/);if(iso)return `${iso[1]}-${iso[2].padStart(2,'0')}-${iso[3].padStart(2,'0')}`;const dmy=n.match(/\b(\d{1,2})[-\/.](\d{1,2})[-\/.](20\d{2})\b/);if(dmy)return `${dmy[3]}-${dmy[2].padStart(2,'0')}-${dmy[1].padStart(2,'0')}`;if(/بعد بكره|بعد بكرة/.test(n))return shiftDate(2);if(/بكره|بكرة|غدا|غدًا/.test(n))return shiftDate(1);if(/النهارده|اليوم/.test(n))return shiftDate(0);return nextWeekday(n)}
function extractTime(text:string){const n=normalize(parseDigits(text));const m=n.match(/(?:الساعه|الساعة|ساعة)?\s*(\d{1,2})(?:\s*[:٫.]\s*(\d{2}))?\s*(صباحا|صباح|ص|مساء|مساءا|م)?/);if(!m)return undefined;let h=Number(m[1]);const mins=m[2]??'00';const mer=m[3];if(h>23||Number(mins)>59)return undefined;if(mer?.startsWith('م')&&h<12)h+=12;if(mer?.startsWith('ص')&&h===12)h=0;return `${String(h).padStart(2,'0')}:${mins}`}
function tokenScore(query:string,target:string){const q=normalize(query);const t=normalize(target);if(!q||!t)return 0;if(q===t)return 1;if(q.includes(t)||t.includes(q))return 0.9;const qs=new Set(q.split(' ').filter(Boolean));const ts=new Set(t.split(' ').filter(Boolean));let overlap=0;for(const x of qs)if([...ts].some(y=>x===y||x.includes(y)||y.includes(x)))overlap++;return overlap/Math.max(qs.size,ts.size,1)}
function topChoices<T extends Choice>(message:string,items:T[],limit:number){return [...items].map(x=>({x,score:tokenScore(message,x.name)})).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.x)}
function intentToCreateSession(message:string){const n=normalize(message);return /(جلسه|جلسات|ميعاد|موعد)/.test(n)&&/(حط|اضف|ضيف|اعمل|حدد|سجل|اكتب|عايز|محتاج|مطلوب|احجز)/.test(n)}
function cleanAction(a:Action){return {...a,lawyerIds:Array.isArray(a.lawyerIds)?a.lawyerIds.filter(Boolean):undefined,description:typeof a.description==='string'?a.description.trim():undefined}}

async function loadMemory(session:SessionLike){const key=`assistant_memory:${session.role==='lawyer'?`lawyer:${session.lawyerId}`:`user:${session.userId}`}`;const row=await prisma.adminSetting.findUnique({where:{key}}).catch(()=>null);if(!row)return {key,facts:{},history:[] as Array<{role:'user'|'assistant';text:string}>};try{const parsed=JSON.parse(row.value);return {key,facts:parsed.facts||{},history:Array.isArray(parsed.history)?parsed.history.slice(-8):[]};}catch{return {key,facts:{},history:[]};}}
async function saveMemory(memory:{key:string;facts:any;history:Array<{role:'user'|'assistant';text:string}>}){await prisma.adminSetting.upsert({where:{key:memory.key},create:{key:memory.key,value:JSON.stringify({facts:memory.facts,history:memory.history.slice(-8)})},update:{value:JSON.stringify({facts:memory.facts,history:memory.history.slice(-8)})}}).catch(()=>undefined)}
async function remember(session:SessionLike,userText:string,assistantText:string,action?:Action){const memory=await loadMemory(session);const facts={...memory.facts};if(action?.locationId)facts.lastLocationId=action.locationId;if(action?.lawyerIds?.length)facts.lastLawyerIds=action.lawyerIds;if(action?.scheduledDate)facts.lastDate=action.scheduledDate;if(action?.scheduledTime)facts.lastTime=action.scheduledTime;if(action?.caseNumber)facts.lastCaseNumber=action.caseNumber;const history=[...memory.history,{role:'user' as const,text:userText.slice(0,600)},{role:'assistant' as const,text:assistantText.slice(0,1200)}];await saveMemory({key:memory.key,facts,history})}

async function context(message:string){const now=new Date();const [tasks,cases,lawyers,locations]=await Promise.all([
  prisma.task.findMany({where:{status:{notIn:['COMPLETED','CANCELLED']},OR:[{scheduledDate:{gte:now}},{scheduledDate:null}]},orderBy:{scheduledDate:'asc'},take:40,include:{location:{select:{name:true,slug:true}},caseRecord:{select:{name:true,number:true,clientName:true}},assignees:{select:{lawyer:{select:{id:true,fullName:true}}}}}}),
  prisma.caseRecord.findMany({orderBy:{id:'desc'},take:80,select:{id:true,name:true,number:true,clientName:true}}),
  prisma.lawyer.findMany({where:{active:true},orderBy:{fullName:'asc'},take:100,select:{id:true,fullName:true,slug:true}}),
  prisma.location.findMany({orderBy:{name:'asc'},take:300,select:{id:true,name:true,slug:true,type:true}})
]);
 const taskItems=tasks.map(t=>({id:t.id,description:t.description,date:t.scheduledDate?.toISOString().slice(0,10)??null,time:t.scheduledTime,location:t.location?.name??null,caseName:t.caseRecord?.name??null,caseNumber:t.caseRecord?.number??null,lawyers:t.assignees.map(a=>a.lawyer.fullName)}));
 return {tasks:taskItems,cases,lawyers,locations,candidateLawyers:topChoices(message,lawyers.map(x=>({id:x.id,name:x.fullName})),12),candidateLocations:topChoices(message,locations.map(x=>({id:x.id,name:x.name})),16),candidateCases:topChoices(message,cases.map(x=>({id:x.id,name:`${x.name} ${x.number}`})),10)};
}
function commonAnswer(message:string,c:any){const n=normalize(message);if(/(ازاي استخدم|كيف استخدم|طريقة استخدام|ابدأ|اعمل ايه)/.test(n)&&!intentToCreateSession(message))return {reply:'أقدر أشرح أي وظيفة وأفتح صفحتها مباشرة. ويمكنك أيضًا كتابة طلبك بصياغتك العادية؛ لا تحتاج استخدام كلمات محددة.',navigation:nav('/admin/guide','الانتقال إلى دليل الاستخدام')};if(/(مواعيد|جلسات|ميعاد|موعد)/.test(n)&&/(اليوم|النهارده)/.test(n)){const today=cairoToday();const items=c.tasks.filter((t:any)=>t.date===today);return {reply:items.length?`مواعيد اليوم (${items.length}):\n${items.slice(0,15).map((t:any)=>`• ${t.time||'بدون وقت'} — ${t.description}${t.location?` — ${t.location}`:''}`).join('\n')}`:'لا توجد جلسات أو مواعيد مسجلة اليوم.',navigation:nav('/calendar','فتح التقويم')}}if(/(قضايا|قضاي|case)/.test(n)&&/(مفتوح|الموجود|كل|قضايا المكتب)/.test(n))return {reply:`يوجد ${c.cases.length} ملف قضية في البيانات الحالية.`,navigation:nav('/admin?tab=cases','فتح القضايا')};return null}
function draftFromMessage(message:string,c:any):Action|null{if(!intentToCreateSession(message))return null;const date=extractDate(message);const time=extractTime(message);const location=topChoices(message,c.locations.map((x:any)=>({id:x.id,name:x.name})),1)[0];const lawyer=topChoices(message,c.lawyers.map((x:any)=>({id:x.id,name:x.fullName})),1)[0];const caseHit=topChoices(message,c.cases.map((x:any)=>({id:x.id,name:`${x.name} ${x.number}`})),1)[0];const missing:string[]=[];if(!date)missing.push('scheduledDate');if(!time)missing.push('scheduledTime');if(!location||tokenScore(message,location.name)<0.45)missing.push('locationId');if(!lawyer||tokenScore(message,lawyer.name)<0.45)missing.push('lawyerIds');const a:Action={type:'create_session',description:caseHit?`جلسة — ${caseHit.name}`:'جلسة جديدة',scheduledDate:date,scheduledTime:time,locationId:location?.id,lawyerIds:lawyer?[lawyer.id]:[],caseName:caseHit?.name?.split(' ').slice(0,-1).join(' '),missing:[...new Set(missing)],choices:{lawyers:c.lawyers.map((x:any)=>({id:x.id,name:x.fullName})),locations:c.locations.map((x:any)=>({id:x.id,name:x.name}))}};return a}
function prepareAction(raw:Action,message:string,c:any,session:SessionLike){const a=cleanAction(raw);if(a.type==='create_session'){a.scheduledDate=a.scheduledDate||extractDate(message);a.scheduledTime=a.scheduledTime||extractTime(message);if(!a.locationId&&a.locationName){a.locationId=topChoices(a.locationName,c.locations.map((x:any)=>({id:x.id,name:x.name})),1)[0]?.id}if(!a.lawyerIds?.length&&a.lawyerNames?.length)a.lawyerIds= a.lawyerNames.map(name=>topChoices(name,c.lawyers.map((x:any)=>({id:x.id,name:x.fullName})),1)[0]?.id).filter(Boolean) as string[];if(session.role==='lawyer'&&session.lawyerId)a.lawyerIds=[session.lawyerId];if(!a.description)a.description=a.caseNumber?`جلسة — قضية ${a.caseNumber}`:'جلسة جديدة';const missing:string[]=[];if(!a.scheduledDate)missing.push('scheduledDate');if(!a.scheduledTime)missing.push('scheduledTime');if(!a.locationId)missing.push('locationId');if(!a.lawyerIds?.length)missing.push('lawyerIds');a.missing=[...new Set(missing)];a.choices={lawyers:c.lawyers.map((x:any)=>({id:x.id,name:x.fullName})),locations:c.locations.map((x:any)=>({id:x.id,name:x.name}))};a.description=`${a.description} — ${a.scheduledDate||'تاريخ غير محدد'} ${a.scheduledTime||'وقت غير محدد'} — ${c.locations.find((x:any)=>x.id===a.locationId)?.name||'مكان غير محدد'} — ${c.lawyers.filter((x:any)=>a.lawyerIds?.includes(x.id)).map((x:any)=>x.fullName).join('، ')||'محامٍ غير محدد'}`;return a}return a}
async function ai(message:string,c:any,memory:any){const dbKey=await prisma.adminSetting.findUnique({where:{key:'assistant_api_key'}}).then(x=>x?.value||'').catch(()=> '');const key=process.env.OPENROUTER_API_KEY||dbKey;if(!key)return null;const model=process.env.OPENROUTER_MODEL||'openrouter/free';const system=`أنت مساعد تشغيلي داخلي لمكتب الدكتور حسام لطفي للمحاماة. افهم العربية المصرية والفصحى والإنجليزية والفرنسية والأخطاء الإملائية. استنتج النية من المعنى وليس من تطابق الكلمات. لا تخترع أي اسم أو ID. عند إنشاء جلسة استخدم فقط lawyer/location IDs من القوائم المعروضة. الجلسة هي Task في قاعدة البيانات وتحتاج: تاريخ، وقت، مكان، ومحامي (أو المحامي الحالي إذا كان المستخدم محاميًا). إذا نقصت بيانات، أرجع action ناقصًا ليطلبها التطبيق. لا تنفذ أي تغيير بنفسك، فقط اقترح action. أعد JSON فقط: {reply:string,navigation?:{path:string,label:string},action?:{type:string,description?:string,scheduledDate?:string,scheduledTime?:string,lawyerIds?:string[],locationId?:string,caseName?:string,caseNumber?:string,clientName?:string,notes?:string,taskId?:string,status?:string}}. الذاكرة المختصرة: ${JSON.stringify(memory.facts)}. آخر المحادثة: ${JSON.stringify(memory.history.slice(-6))}. محامون محتملون: ${JSON.stringify(c.candidateLawyers)}. أماكن محتملة: ${JSON.stringify(c.candidateLocations)}. قضايا محتملة: ${JSON.stringify(c.candidateCases)}.`;const r=await fetch(OPENROUTER_URL,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','HTTP-Referer':process.env.NEXT_PUBLIC_APP_URL||'https://dr-hossam-lotfy-hw88.vercel.app','X-Title':'Dr Hossam Lotfy Office Assistant'},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:message}],temperature:0.1,response_format:{type:'json_object'}})});if(!r.ok)throw new Error(`AI provider ${r.status}`);const d=await r.json();const text=d.choices?.[0]?.message?.content||'{}';try{return JSON.parse(text)}catch{const m=text.match(/\{[\s\S]*\}/);return m?JSON.parse(m[0]):null}}

export const POST=handle(async(req:Request)=>{const session=await user() as SessionLike|null;if(!session) return json({error:'يجب تسجيل الدخول لاستخدام مساعد المكتب'},{status:401});const data=await readJson(req as never,bodySchema);const c=await context(data.message);const memory=await loadMemory(session);
 if(data.confirm&&data.action){const a=prepareAction(data.action as Action,data.message,c,session);if(a.missing?.length)return json({reply:'ما زالت هناك بيانات أساسية ناقصة. أكملها أولًا.',action:a});if(session.role==='lawyer'&&a.lawyerIds?.some(id=>id!==session.lawyerId))return json({error:'المحامي يمكنه إنشاء جلسة لنفسه فقط.'},{status:403});
  if(a.type==='create_session'||a.type==='create_task'){if(!a.locationId)return json({reply:'مكان الجلسة مطلوب.',action:{...a,missing:['locationId']}});const validLocation=await prisma.location.findUnique({where:{id:a.locationId}});if(!validLocation)return json({reply:'المكان المحدد غير موجود.',action:{...a,locationId:undefined,missing:['locationId']}});const lawyerIds=(a.lawyerIds||[]).filter(Boolean);const lawyers=lawyerIds.length?await prisma.lawyer.findMany({where:{id:{in:lawyerIds},active:true},select:{id:true,fullName:true}}):[];if(lawyerIds.length!==lawyers.length)return json({reply:'أحد المحامين المحددين غير موجود أو غير نشط.',action:{...a,lawyerIds:[],missing:['lawyerIds']}});let caseId:string|undefined;if(a.caseName||a.caseNumber){let existing=null as {id:string;clientName:string|null}|null;if(a.caseNumber)existing=await prisma.caseRecord.findFirst({where:{number:a.caseNumber},select:{id:true,clientName:true}});if(!existing&&a.caseName)existing=await prisma.caseRecord.findFirst({where:{name:a.caseName},select:{id:true,clientName:true}});caseId=existing?.id;if(!existing){const createdCase=await prisma.caseRecord.create({data:{name:a.caseName||`قضية ${a.caseNumber||''}`.trim(),number:a.caseNumber||`ASSIST-${Date.now()}`,clientName:a.clientName?.trim()||null}});caseId=createdCase.id;}}
    const created=await prisma.task.create({data:{locationId:a.locationId,caseId,description:(a.description||'جلسة جديدة').split(' — ')[0],notes:a.notes?.trim()||null,scheduledDate:new Date(`${a.scheduledDate}T00:00:00`),scheduledTime:a.scheduledTime,createdById:session.role==='admin'?session.userId:undefined,authorId:session.role==='lawyer'?session.lawyerId:undefined,assignees:{create:lawyerIds.map(id=>({lawyer:{connect:{id}}}))}}});await logActivity({action:'CREATED',summary:`أنشأ المساعد جلسة: ${(a.description||'جلسة جديدة').slice(0,80)}`,taskId:created.id,locationId:a.locationId,byUserId:session.role==='admin'?session.userId:undefined,byLawyerId:session.role==='lawyer'?session.lawyerId:undefined}).catch(()=>undefined);if(lawyerIds.length)await notifyTaskAssigned(lawyerIds,(a.description||'جلسة جديدة').slice(0,60),`${a.scheduledDate} — ${a.scheduledTime}`,`/sessions/${created.id}`).catch(()=>undefined);const reply=`تمت إضافة الجلسة بنجاح في ${a.scheduledDate} الساعة ${a.scheduledTime} في ${validLocation.name}.`;await remember(session,data.message,reply,{...a,description:a.description});return json({ok:true,success:true,reply,navigation:nav(`/sessions/${created.id}`,'فتح الجلسة')});}
  if(a.type==='update_task'){const task=await prisma.task.findUnique({where:{id:a.taskId}});if(!task)return json({error:'المهمة غير موجودة'},{status:404});const updated=await prisma.task.update({where:{id:task.id},data:{...(a.description?{description:a.description}:{}) ,...(a.scheduledDate?{scheduledDate:new Date(`${a.scheduledDate}T00:00:00`)}:{}),...(a.scheduledTime?{scheduledTime:a.scheduledTime}:{}),...(a.status?{status:a.status as any}:{}),...(a.locationId?{locationId:a.locationId}:{})}});const reply='تم تعديل المهمة بنجاح.';await remember(session,data.message,reply,a);return json({ok:true,success:true,reply,navigation:nav(`/sessions/${updated.id}`,'فتح المهمة')});}}
 const common=commonAnswer(data.message,c);if(common){await remember(session,data.message,common.reply);return json(common)}
 let proposed=draftFromMessage(data.message,c);if(!proposed){const aiOut=await ai(data.message,c,memory);if(aiOut?.action)proposed=prepareAction(aiOut.action,data.message,c,session);if(proposed&&aiOut?.reply)proposed=prepareAction({...proposed,description:aiOut.reply},data.message,c,session);if(aiOut&&proposed)return json({reply:aiOut.reply||'فهمت طلبك. راجع البيانات قبل التنفيذ.',navigation:aiOut.navigation,action:proposed});if(aiOut){await remember(session,data.message,aiOut.reply||'تم الرد.');return json(aiOut)}}if(proposed){await remember(session,data.message,proposed.missing?.length?'طلبت بيانات إضافية لإكمال الجلسة.':`أعددت طلب جلسة للتأكيد: ${proposed.description}`,proposed);return json({reply:proposed.missing?.length?'عشان أضيف الجلسة محتاج البيانات الناقصة فقط. راجع الحقول التالية:':'فهمت الطلب. راجع بيانات الجلسة التالية ثم أكد التنفيذ.',action:proposed});}
 const fallback={reply:'فهمت طلبك. اكتب المطلوب بطريقتك الطبيعية، ولو كان فيه إضافة أو تعديل في البيانات سأجمع البيانات الأساسية معك ثم أطلب التأكيد قبل التنفيذ.'};await remember(session,data.message,fallback.reply);return json(fallback);
});

export const GET=handle(async()=>{const session=await user() as SessionLike|null;if(!session)return json({error:'غير مسجل الدخول'},{status:401});const memory=await loadMemory(session);const db=await prisma.adminSetting.findUnique({where:{key:'assistant_api_key'}}).catch(()=>null);return json({configured:Boolean(process.env.OPENROUTER_API_KEY||db?.value),source:process.env.OPENROUTER_API_KEY?'environment':db?.value?'admin':'none',model:process.env.OPENROUTER_MODEL||'openrouter/free',history:memory.history,facts:memory.facts});});
