import { z } from 'zod';
import { handle, json, readJson, requirePermission, user } from '@/lib/api';
import { prisma } from '@/lib/prisma';
import { logActivity } from '@/lib/activity';
import { slugify, uniqueSlug } from '@/lib/slug';
import { isSeniorManagement } from '@/lib/office-workflow';
const LOCATION_TYPES=['COURT','TAX_OFFICE','COMMERCIAL_REGISTRY','CIVIL_REGISTRY','PROSECUTION','LAWYERS_SYNDICATE','SURVEY_AUTHORITY','PASSPORTS','TRAFFIC','SOCIAL_INSURANCE','LABOR_OFFICE','CUSTOMS','INVESTMENT_AGENCY','EXPERTS_OFFICE','REAL_ESTATE_REGISTRATION','GOVERNMENT_AGENCY','OTHER'] as const;
const optionalText=(max:number)=>z.string().max(max).optional().nullable();
const updateSchema=z.object({name:z.string().min(2).max(150).optional(),nameEn:optionalText(150),type:z.enum(LOCATION_TYPES).optional(),subType:optionalText(100),governorate:optionalText(80),city:optionalText(80),district:optionalText(80),lat:z.number().min(-90).max(90).nullable().optional(),lng:z.number().min(-180).max(180).nullable().optional(),workingHours:optionalText(200),services:z.array(z.string().max(120)).max(30).optional(),jurisdiction:optionalText(300),requiresPersonal:z.boolean().optional(),hasOnlineService:z.boolean().optional(),source:optionalText(200),confidence:optionalText(40),distanceFromDokki:z.number().min(0).max(5000).nullable().optional(),distanceBucket:optionalText(20),buildingId:optionalText(100),description:optionalText(1000),searchKeywords:z.array(z.string().max(60)).max(40).optional()});
export async function GET(req:Request){const u=new URL(req.url);const type=u.searchParams.get('type');const governorate=u.searchParams.get('governorate');const q=u.searchParams.get('q')?.trim();const where:any={};if(type&&(LOCATION_TYPES as readonly string[]).includes(type))where.type=type;if(governorate)where.governorate=governorate;if(q)where.OR=[{name:{contains:q,mode:'insensitive'}},{nameEn:{contains:q,mode:'insensitive'}}];const locations=await prisma.location.findMany({where,orderBy:[{type:'asc'},{name:'asc'}],include:{tasks:{where:{scheduledDate:{gte:new Date()},status:{notIn:['COMPLETED','CANCELLED']}},select:{scheduledDate:true}}}});return json({locations:locations.map(l=>({id:l.id,slug:l.slug,name:l.name,nameEn:l.nameEn,type:l.type,subType:l.subType,governorate:l.governorate,city:l.city,district:l.district,workingHours:l.workingHours,distanceBucket:l.distanceBucket,distanceFromDokki:l.distanceFromDokki,upcoming:l.tasks.length,nextTaskDate:l.tasks.length?l.tasks.map(t=>t.scheduledDate).filter(Boolean).sort()[0]?.toISOString().slice(0,10)??null:null}))});}
export const POST=handle(async(req:Request)=>{const session=await user();const senior=await isSeniorManagement(session);if(!session||(session.role!=='admin'&&!senior))return json({error:'صلاحية الإدارة مطلوبة'},{status:403});const data=await readJson(req, z.object({name:z.string().min(2).max(150),nameEn:optionalText(150),type:z.enum(LOCATION_TYPES),subType:optionalText(100),governorate:optionalText(80),city:optionalText(80),district:optionalText(80),lat:z.number().min(-90).max(90).nullable().optional(),lng:z.number().min(-180).max(180).nullable().optional(),workingHours:optionalText(200),services:z.array(z.string().max(120)).max(30).optional(),jurisdiction:optionalText(300),requiresPersonal:z.boolean().optional(),hasOnlineService:z.boolean().optional(),source:optionalText(200),confidence:optionalText(40),distanceFromDokki:z.number().min(0).max(5000).nullable().optional(),distanceBucket:optionalText(20),buildingId:optionalText(100),description:optionalText(1000),searchKeywords:z.array(z.string().max(60)).max(40).optional()}));const name=data.name.trim();const exists=await prisma.location.findFirst({where:{OR:[{name},{slug:slugify(name)}]}});if(exists)return json({error:'يوجد مكان بهذا الاسم بالفعل'},{status:409});const slug=await uniqueSlug(slugify(name));const location=await prisma.location.create({data:{name,slug,type:data.type,nameEn:data.nameEn?.trim()||null,subType:data.subType?.trim()||null,governorate:data.governorate?.trim()||null,city:data.city?.trim()||null,district:data.district?.trim()||null,lat:data.lat??null,lng:data.lng??null,workingHours:data.workingHours?.trim()||null,services:data.services??[],jurisdiction:data.jurisdiction?.trim()||null,requiresPersonal:data.requiresPersonal??false,hasOnlineService:data.hasOnlineService??false,source:data.source?.trim()||null,confidence:data.confidence?.trim()||null,distanceFromDokki:data.distanceFromDokki??null,distanceBucket:data.distanceBucket?.trim()||null,buildingId:data.buildingId?.trim()||null,description:data.description?.trim()||null,searchKeywords:data.searchKeywords??[]}});await logActivity({action:'LOCATION_ADDED',summary:`أضاف مكاناً جديداً: ${name}`,locationId:location.id,byUserId:session.role==='admin'?session.userId:null,byLawyerId:session.role==='lawyer'?session.lawyerId:null});return json({ok:true,location:{id:location.id,slug:location.slug}},{status:201});});
export const PATCH=handle(async(req:Request,ctx:{params:Promise<{id:string}>})=>{const session=await user();const senior=await isSeniorManagement(session);if(!session||(session.role!=='admin'&&!senior))return json({error:'صلاحية الإدارة مطلوبة'},{status:403});const{id}=await ctx.params;const location=await prisma.location.findUnique({where:{id}});if(!location)return json({error:'المكان غير موجود'},{status:404});const data=await readJson(req,updateSchema);const clean=Object.fromEntries(Object.entries(data).map(([k,v])=>[k,typeof v==='string'&&v.trim()===''?null:v]));const updated=await prisma.location.update({where:{id},data:clean});await logActivity({action:'EDITED',summary:`عدّل بيانات مكان: ${updated.name}`,locationId:id,byUserId:session.role==='admin'?session.userId:null,byLawyerId:session.role==='lawyer'?session.lawyerId:null});return json({ok:true,location:updated});});
export const DELETE=handle(async(_req:Request,ctx:{params:Promise<{id:string}>})=>{const session=await requirePermission('manageLocations');const{id}=await ctx.params;const location=await prisma.location.findUnique({where:{id},include:{tasks:true}});if(!location)return json({error:'المكان غير موجود'},{status:404});if(location.tasks.length>0)return json({error:'لا يمكن حذف مكان له جلسات أو مهام مسجلة.'},{status:409});await prisma.location.delete({where:{id}});await logActivity({action:'DELETED',summary:`حذف مكاناً: ${location.name}`,byUserId:session.userId});return json({ok:true});});
