import { NextResponse } from 'next/server';
import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { user } from '@/lib/api';
import { createOfficeRequest, isSeniorManagement, officeId, notifySenior } from '@/lib/office-workflow';
import { escapeTelegramHtml, sendTelegramGroupNotification } from '@/lib/telegram';
import { appOrigin } from '@/lib/google-oauth';

export async function GET(_req:Request,{params}:{params:Promise<{id:string}>}){const session=await user();if(!session)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});const{id}=await params;const[feedback,followups]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "task_feedback" WHERE "task_id"=$1`,id),prisma.$queryRawUnsafe<any[]>(`SELECT f.*,t."description",t."scheduledDate",t."scheduledTime" FROM "task_followups" f JOIN "tasks" t ON t."id"=f."child_task_id" WHERE f."parent_task_id"=$1 ORDER BY f."created_at" DESC`,id)]);return NextResponse.json({feedback:feedback[0]||null,followups});}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const session=await user();if(!session)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});const{id}=await params;const data=z.object({feedback:z.string().max(5000).optional(),result:z.string().max(2000).optional(),followup:z.object({description:z.string().min(2),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),time:z.string().regex(/^\d{2}:\d{2}$/).optional(),locationId:z.string().optional(),lawyerIds:z.array(z.string()).max(20).optional(),relationType:z.enum(['APPEAL','CHALLENGE','FOLLOW_UP','RELATED']).default('FOLLOW_UP')}).optional()}).parse(await req.json());
 const senior=await isSeniorManagement(session);
 if(data.feedback!==undefined||data.result!==undefined){if(!senior){const rid=await createOfficeRequest({type:'TASK_EDIT',title:'تحديث نتيجة جلسة',reason:data.feedback||data.result||'',payload:{taskId:id,feedback:data.feedback,result:data.result},targetEntityType:'task',targetEntityId:id,session});await notifySenior('طلب تحديث جلسة',`طلب تعديل نتيجة الجلسة ${id}`,'/admin/office');return NextResponse.json({ok:true,requiresApproval:true,requestId:rid});}await prisma.$executeRawUnsafe(`INSERT INTO "task_feedback" ("id","task_id","feedback","result","created_by_user_id","created_by_lawyer_id","updated_at") VALUES ($1,$2,$3,$4,$5,$6,NOW()) ON CONFLICT ("task_id") DO UPDATE SET "feedback"=$3,"result"=$4,"updated_at"=NOW()`,officeId('feedback'),id,data.feedback??null,data.result??null,session.role==='admin'?session.userId:null,session.role==='lawyer'?session.lawyerId:null);}
 if(data.followup){const f=data.followup;if(!f.locationId)return NextResponse.json({error:'المكان مطلوب للمعاد الجديد'},{status:400});if(!senior){const rid=await createOfficeRequest({type:'TASK_FOLLOWUP',title:`معاد لاحق للجلسة ${id}`,reason:f.relationType,payload:{parentTaskId:id,...f},targetEntityType:'task',targetEntityId:id,session});await notifySenior('طلب معاد لاحق',`يوجد طلب معاد مرتبط بجلسة ${id}`,'/admin/office');return NextResponse.json({ok:true,requiresApproval:true,requestId:rid});}
 const parent=await prisma.$queryRawUnsafe<Array<{branch_id:string|null;caseId:string|null}>>(`SELECT "branch_id","caseId" FROM "tasks" WHERE "id"=$1 LIMIT 1`,id);const branchId=parent[0]?.branch_id||'branch_main';const taskId=officeId('task');await prisma.$executeRawUnsafe(`INSERT INTO "tasks" ("id","locationId","description","notes","scheduledDate","scheduledTime","status","branch_id","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5::date,$6,'PENDING',$7,NOW(),NOW())`,taskId,f.locationId,f.description,`مرتبط بالجلسة ${id}` ,f.date??null,f.time??null,branchId);for(const lid of f.lawyerIds||[]){await prisma.$executeRawUnsafe(`INSERT INTO "task_assignments" ("id","taskId","lawyerId","createdAt") VALUES ($1,$2,$3,NOW()) ON CONFLICT ("taskId","lawyerId") DO NOTHING`,officeId('assign'),taskId,lid);}await prisma.$executeRawUnsafe(`INSERT INTO "task_followups" ("id","parent_task_id","child_task_id","relation_type","created_by_user_id","created_by_lawyer_id") VALUES ($1,$2,$3,$4,$5,$6)`,officeId('follow'),id,taskId,f.relationType,session.role==='admin'?session.userId:null,session.role==='lawyer'?session.lawyerId:null);await sendTelegramGroupNotification(['<b>📌 معاد/تكليف متابعة جديد</b>','', '<b>التكليف:</b> '+escapeTelegramHtml(f.description),'<b>النوع:</b> '+escapeTelegramHtml(f.relationType),f.date?'<b>التاريخ:</b> '+escapeTelegramHtml(f.date):null,f.time?'<b>الوقت:</b> '+escapeTelegramHtml(f.time):null,'<b>الفرع:</b> '+escapeTelegramHtml(branchId),'<b>الجلسة الأصلية:</b> '+escapeTelegramHtml(id),'','<a href="'+appOrigin()+'/sessions/'+taskId+'">فتح التكليف</a>'].filter(Boolean).join('\\n')).catch((error)=>{console.error('Follow-up Telegram notification failed:',error)});return NextResponse.json({ok:true,taskId});}
 return NextResponse.json({ok:true});}
