'use client';
import * as React from 'react';
import { Check, X, ClipboardList } from 'lucide-react';
const groups:[string,string[]][]=[['الإجازات',['LEAVE']],['التعديلات',['PROFILE_EDIT','TASK_EDIT','CASE_EDIT','CLIENT_STATUS']],['التكليف والتنفيذ',['TASK_DELEGATE','TASK_CREATE','TASK_CREATE_SESSION','TASK_FOLLOWUP','TASK_COMPLETE_FOR_COLLEAGUE']],['المسح',['DELETE']],['المالية',['FINANCE']],['طلبات عامة',['GENERAL']]];
export function RequestGroupsClient(){
 const[data,setData]=React.useState<any[]>([]);const[busy,setBusy]=React.useState(false);
 const load=React.useCallback(async()=>{setBusy(true);try{const r=await fetch('/api/admin/office',{cache:'no-store'});const j=await r.json();if(r.ok)setData(j.requests||[]);}finally{setBusy(false)}},[]);React.useEffect(()=>{void load()},[load]);
 const decide=async(id:string,decision:'APPROVED'|'REJECTED')=>{setBusy(true);try{const r=await fetch('/api/admin/office/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,decision})});const j=await r.json();if(!r.ok)throw new Error(j.error||'فشل القرار');await load()}catch(e){alert(e instanceof Error?e.message:'فشل القرار')}finally{setBusy(false)}};
 const classify=(type:string)=>groups.find(([_,types])=>types.includes(type))?.[0]||'طلبات عامة';
 return <section className="space-y-4" dir="rtl"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold text-navy-950"><ClipboardList size={18} className="inline me-2 text-gold-600"/>طلبات الإدارة</h2><span className="text-xs text-navy-400">{data.filter(r=>r.status==='PENDING').length} معلّق</span></div>{groups.map(([label])=>{const items=data.filter(r=>classify(r.type)===label);if(!items.length)return null;return <section key={label} className="rounded-2xl border border-navy-100 bg-white p-4 shadow-sm"><h3 className="mb-3 text-sm font-extrabold text-navy-900">{label}</h3><div className="space-y-2">{items.map(r=><div key={r.id} className="rounded-xl border border-navy-100 bg-ivory-50 p-3"><div className="flex items-start justify-between gap-3"><div><b className="text-sm text-navy-900">{r.title}</b><div className="mt-1 text-[11px] text-navy-400">{r.type} · {r.requester_lawyer_name||r.requester_user_name||'حساب'} · {new Date(r.created_at).toLocaleString('ar-EG')}</div>{r.reason&&<p className="mt-2 text-xs leading-6 text-navy-600">{r.reason}</p>}</div>{r.status==='PENDING'&&<div className="flex gap-2"><button disabled={busy} onClick={()=>void decide(r.id,'APPROVED')} className="rounded-lg bg-emerald-600 p-2 text-white"><Check size={14}/></button><button disabled={busy} onClick={()=>void decide(r.id,'REJECTED')} className="rounded-lg bg-red-600 p-2 text-white"><X size={14}/></button></div>}</div></div>)}</div></section>})}{!data.length&&<div className="rounded-2xl border border-dashed p-8 text-center text-sm text-navy-400">لا توجد طلبات مسجلة.</div>}</section>;
}
