'use client';
import * as React from 'react';
import { Landmark, UserPlus, X, Loader2 } from 'lucide-react';
import { Button, Field, Input, Modal, Select } from './ui';
import { LOCATION_TYPE_LABEL } from '@/lib/constants';
import { toastError, toastSuccess } from '../toasts';
export function SeniorAdminActions(){
 const[modal,setModal]=React.useState<'lawyer'|'location'|null>(null);const[busy,setBusy]=React.useState(false);
 const[fullName,setFullName]=React.useState('');const[title,setTitle]=React.useState<'ADVOCATE'|'DOCTOR'>('ADVOCATE');const[phone,setPhone]=React.useState('');const[email,setEmail]=React.useState('');const[specialization,setSpecialization]=React.useState('');
 const[name,setName]=React.useState('');const[nameEn,setNameEn]=React.useState('');const[type,setType]=React.useState('COURT');const[governorate,setGovernorate]=React.useState('');const[city,setCity]=React.useState('');const[district,setDistrict]=React.useState('');
 const reset=()=>{setFullName('');setTitle('ADVOCATE');setPhone('');setEmail('');setSpecialization('');setName('');setNameEn('');setType('COURT');setGovernorate('');setCity('');setDistrict('');};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const body=modal==='lawyer'?{action:'lawyer_add',fullName,title,phone,email,specialization}:{action:'location_add',name,nameEn,type,governorate,city,district};const r=await fetch('/api/admin/office',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'تعذر الحفظ');toastSuccess(modal==='lawyer'?'تمت إضافة زميل العمل ✓':'تمت إضافة مكان العمل ✓');setModal(null);reset()}catch(e){toastError(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}};
 const types=Object.keys(LOCATION_TYPE_LABEL);
 return <><div className="flex flex-wrap gap-2" dir="rtl"><Button size="sm" onClick={()=>setModal('lawyer')}><UserPlus size={14}/>+ إضافة محامي</Button><Button size="sm" variant="outline" onClick={()=>setModal('location')}><Landmark size={14}/>+ إضافة محكمة أو جهة</Button></div>
 <Modal open={modal==='lawyer'} onClose={()=>{if(!busy)setModal(null)}} title="إضافة محامي جديد" wide footer={<div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setModal(null)}>إلغاء</Button><Button type="submit" form="senior-lawyer-form" disabled={busy}>{busy&&<Loader2 size={14} className="animate-spin"/>}إضافة</Button></div>}><form id="senior-lawyer-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="الاسم الثلاثي" required><Input value={fullName} onChange={e=>setFullName(e.target.value)} required/></Field><Field label="الصفة" required><Select value={title} onChange={e=>setTitle(e.target.value as any)}><option value="ADVOCATE">محامي</option><option value="DOCTOR">دكتور</option></Select></Field><Field label="الهاتف" required><Input value={phone} onChange={e=>setPhone(e.target.value)} required dir="ltr"/></Field><Field label="البريد الإلكتروني"><Input value={email} onChange={e=>setEmail(e.target.value)} type="email" dir="ltr"/></Field><Field label="التخصص"><Input value={specialization} onChange={e=>setSpecialization(e.target.value)}/></Field></form></Modal>
 <Modal open={modal==='location'} onClose={()=>{if(!busy)setModal(null)}} title="إضافة محكمة أو جهة" wide footer={<div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setModal(null)}>إلغاء</Button><Button type="submit" form="senior-location-form" disabled={busy}>{busy&&<Loader2 size={14} className="animate-spin"/>}إضافة</Button></div>}><form id="senior-location-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="اسم المكان" required><Input value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="الاسم بالإنجليزية"><Input value={nameEn} onChange={e=>setNameEn(e.target.value)} dir="ltr"/></Field><Field label="النوع" required><Select value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t} value={t}>{LOCATION_TYPE_LABEL[t]}</option>)}</Select></Field><Field label="المحافظة"><Input value={governorate} onChange={e=>setGovernorate(e.target.value)}/></Field><Field label="المدينة"><Input value={city} onChange={e=>setCity(e.target.value)}/></Field><Field label="الحي / المنطقة"><Input value={district} onChange={e=>setDistrict(e.target.value)}/></Field></form></Modal></>
}
