import type {Metadata} from 'next';import Link from 'next/link';import {Archive,Users,BriefcaseBusiness,Settings,ShieldCheck,Building2} from 'lucide-react';import {redirect} from 'next/navigation';import {getCurrentUser} from '@/lib/auth';import {prisma} from '@/lib/prisma';import {getAdminStats,getBranchAdminStats,getFeed} from '@/lib/queries';import {AdminShell} from '@/components/admin/admin-shell';import {permissionsOf} from '@/lib/rbac';
import {getBranchScope,getAllBranches} from '@/lib/branch-access';
import {isSeniorManagement} from '@/lib/office-workflow';import {Card} from '@/components/ui';export const metadata:Metadata={title:'منطقة الإدارة'}; // Legacy administration layout intentionally unchanged.
export default async function AdminPage({searchParams}:{searchParams?:Promise<{branchId?:string}>}){const session=await getCurrentUser();if(!session)redirect('/auth');const params=await searchParams??{};const requestedBranchId=typeof params.branchId==='string'&&params.branchId.trim()?params.branchId.trim():null;const senior=await isSeniorManagement(session);if(senior&&!requestedBranchId)redirect('/admin/office');const branchScope=await getBranchScope(session);if(!senior&&(branchScope.officeManager||branchScope.financeManager)&&!requestedBranchId)redirect('/admin/office');let adminIdentity:{userId:string;name:string;role:string}|null=null;if(session.role==='admin')adminIdentity={userId:session.userId,name:session.name,role:session.userRole};else if(session.isAdmin){const row=await prisma.lawyer.findUnique({where:{id:session.lawyerId},select:{email:true,googleEmail:true}});const email=row?.googleEmail||row?.email;if(email){const account=await prisma.user.findUnique({where:{email:email.toLowerCase().trim()},select:{id:true,name:true,role:true}});if(account&&(account.role==='SUPER_ADMIN'||account.role==='ADMIN'))adminIdentity={userId:account.id,name:session.name,role:'SUPER_ADMIN'}}}if(!adminIdentity&&senior)adminIdentity={userId:session.lawyerId,name:session.name,role:'SUPER_ADMIN'};if(!adminIdentity)redirect('/');const allBranches=await getAllBranches();if(requestedBranchId){if(!branchScope.allBranches&&!branchScope.branchIds.includes(requestedBranchId))redirect('/admin/office');if(!allBranches.some((b:any)=>b.id===requestedBranchId))redirect('/admin/office');}const branches=branchScope.allBranches?allBranches:allBranches.filter((b:any)=>branchScope.branchIds.includes(b.id));

let stats:Awaited<ReturnType<typeof getAdminStats>>;
let lawyers:any[]=[];
let locations:any[]=[];
let cases:any[]=[];
let categories:any[]=[];
let caseCategoryRows:any[]=[];
let feed:{items:any[]};
let activity:any[]=[];
let notifications:any[]=[];
let lawyerBranches:any[]=[];

if(requestedBranchId){
  const branchId=requestedBranchId;
  const taskRows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "tasks" WHERE COALESCE("branch_id",'branch_main')=$1 ORDER BY "createdAt" DESC LIMIT 1000`,branchId);
  const taskIds=taskRows.map((row)=>row.id);
  [stats,lawyers,locations,cases,categories,activity,notifications,feed]=await Promise.all([
    getBranchAdminStats(branchId),
    prisma.$queryRawUnsafe<any[]>(`SELECT l."id",l."slug",l."fullName",l."title",l."phone",l."email",l."googleEmail",l."specialization",l."bio",l."position",l."profilePhotoUrl" AS "photo",l."isPrincipal",l."active",l."approvedAt",COUNT(ta."id") FILTER (WHERE ta."completedAt" IS NULL AND t."status" NOT IN ('CANCELLED') AND (t."scheduledDate" >= CURRENT_DATE OR t."scheduledDate" IS NULL))::int AS "upcoming" FROM "office_branch_lawyers" bl INNER JOIN "lawyers" l ON l."id"=bl."lawyer_id" LEFT JOIN "task_assignments" ta ON ta."lawyerId"=l."id" LEFT JOIN "tasks" t ON t."id"=ta."taskId" AND t."branch_id"=$1 WHERE bl."branch_id"=$1 GROUP BY l."id",l."slug",l."fullName",l."title",l."phone",l."email",l."googleEmail",l."specialization",l."bio",l."position",l."profilePhotoUrl",l."isPrincipal",l."active",l."approvedAt" ORDER BY l."sortOrder",l."fullName"`,branchId),
    prisma.location.findMany({select:{id:true,slug:true,name:true,nameEn:true,type:true,subType:true,governorate:true,city:true,district:true,workingHours:true,jurisdiction:true,distanceBucket:true,services:true,description:true},orderBy:[{type:'asc'},{name:'asc'}]}),
    prisma.$queryRawUnsafe<any[]>(`SELECT c."id",c."name",c."number",c."clientName",c."category_id",c."branch_id" FROM "case_records" c WHERE c."branch_id"=$1 ORDER BY c."id" DESC LIMIT 100`,branchId),
    prisma.$queryRawUnsafe<any[]>(`SELECT "id","name_ar","name_en","sort_order","active" FROM "office_case_categories" ORDER BY "sort_order","name_ar"`),
    prisma.activityLog.findMany({where:taskIds.length?{OR:[{taskId:{in:taskIds}},{lawyerId:{in:lawyers.map((l:any)=>l.id)}}]}:undefined,orderBy:{createdAt:'desc'},take:12}),
    prisma.notification.findMany({where:{userId:adminIdentity.userId},orderBy:{createdAt:'desc'},take:30}),
    getFeed({taskIds,limit:15}),
  ]);
  const caseIds=cases.map((c:any)=>c.id);
  const eventRows=caseIds.length?await prisma.$queryRawUnsafe<any[]>(`SELECT "id","caseId","description","type","authorName","createdAt" FROM "case_events" WHERE "caseId"=ANY($1::text[]) ORDER BY "createdAt" DESC`,caseIds):[];
  cases=cases.map((c:any)=>({...c,events:eventRows.filter((e:any)=>e.caseId===c.id).slice(0,100)}));
}else{
  [stats,lawyers,locations,cases,categories,caseCategoryRows,feed,activity,notifications,lawyerBranches]=await Promise.all([
    getAdminStats(),
    prisma.lawyer.findMany({orderBy:[{sortOrder:'asc'},{fullName:'asc'}],include:{assignments:{where:{task:{status:{notIn:['COMPLETED','CANCELLED']},OR:[{scheduledDate:{gte:new Date()}},{scheduledDate:null}]}}}}}),
    prisma.location.findMany({select:{id:true,slug:true,name:true,nameEn:true,type:true,subType:true,governorate:true,city:true,district:true,workingHours:true,jurisdiction:true,distanceBucket:true,services:true,description:true},orderBy:[{type:'asc'},{name:'asc'}]}),
    prisma.caseRecord.findMany({orderBy:{id:'desc'},take:100,include:{events:{orderBy:{createdAt:'desc'},take:100}}}),
    prisma.$queryRawUnsafe<any[]>(`SELECT "id","name_ar","name_en","sort_order","active" FROM "office_case_categories" ORDER BY "sort_order","name_ar"`),
    prisma.$queryRawUnsafe<any[]>(`SELECT "id","category_id" FROM "case_records" WHERE "archived_at" IS NULL`),
    getFeed({limit:15}),
    prisma.activityLog.findMany({orderBy:{createdAt:'desc'},take:12,include:{lawyer:{select:{fullName:true,slug:true}}}}),
    prisma.notification.findMany({where:{userId:adminIdentity.userId},orderBy:{createdAt:'desc'},take:30}),
    prisma.$queryRawUnsafe<any[]>(`SELECT bl."lawyer_id",ob."name_ar" AS "branch_name" FROM "office_branch_lawyers" bl INNER JOIN "office_branches" ob ON ob."id"=bl."branch_id" ORDER BY bl."lawyer_id"`)
  ]);
}return (<><div className="mx-auto w-full max-w-[1440px] px-4 pt-5 sm:px-6"><div className="mb-4 grid gap-2 md:grid-cols-3">
<div className="flex flex-wrap items-center gap-2 rounded-2xl border border-gold-200 bg-white p-2"><span className="px-2 text-[10px] font-black text-gold-700">الإدارة</span><Link href="/admin/office" className="inline-flex items-center gap-2 rounded-xl bg-navy-950 px-4 py-2 text-[11px] font-extrabold text-white"><ShieldCheck size={14}/> مركز الإدارة</Link><Link href="/admin/settings" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-[11px] font-extrabold text-navy-700 hover:bg-ivory-50"><Settings size={14} className="text-gold-600"/> إعدادات المساعد</Link></div>
<div className="flex flex-wrap items-center gap-2 rounded-2xl border border-navy-100 bg-white p-2"><span className="px-2 text-[10px] font-black text-gold-700">الموارد</span><Link href="/admin/clients" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-[11px] font-extrabold text-navy-700 hover:bg-ivory-50"><Users size={14} className="text-gold-600"/> قائمة العملاء</Link><Link href="/admin/lawyers/archive" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-[11px] font-extrabold text-navy-700 hover:bg-ivory-50"><Archive size={14} className="text-gold-600"/> زملاء العمل السابقين</Link></div>
<div className="md:col-span-3 flex flex-wrap items-center gap-2 rounded-2xl border border-gold-200 bg-white p-2"><span className="px-2 text-[10px] font-black text-gold-700">المكاتب والفروع</span>{branches.map((b:any)=><Link key={b.id} href={"/admin/office/branches/"+b.id} className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-[11px] font-extrabold text-navy-700 hover:bg-ivory-50"><Building2 size={14} className="text-gold-600"/>{b.name_ar}</Link>)}<Link href="/admin/office" className="ms-auto inline-flex items-center gap-2 rounded-xl bg-navy-950 px-3 py-2 text-[11px] font-extrabold text-white"><ShieldCheck size={14}/> إدارة الفروع</Link></div>
</div>{requestedBranchId && <div className="mb-4 flex items-center gap-2 rounded-2xl border border-gold-200 bg-white px-4 py-3"><Building2 size={16} className="text-gold-600"/><span className="text-[11px] font-extrabold text-navy-400">المكتب الحالي:</span><strong className="text-[13px] font-extrabold text-navy-950">{branches.find((b:any)=>b.id===requestedBranchId)?.name_ar??requestedBranchId}</strong></div>}<Card className="mb-5 flex items-center gap-4 border-gold-200 bg-gradient-to-l from-white to-gold-50/40 p-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-gold-500/10 text-gold-700"><BriefcaseBusiness size={20}/></span><div><p className="text-[10px] font-extrabold text-navy-400">عداد القضايا في المكتب</p><strong className="text-3xl font-extrabold text-navy-950">{stats.cases}</strong><span className="ms-2 text-xs font-bold text-navy-400">قضية</span></div></Card></div><AdminShell branchId={requestedBranchId??undefined} branchName={requestedBranchId?(branches.find((b:any)=>b.id===requestedBranchId)?.name_ar??null):null} session={adminIdentity} permissions={permissionsOf('SUPER_ADMIN')} stats={stats} lawyers={lawyers.map(l=>({id:l.id,slug:l.slug,name:l.fullName,title:l.title,phone:l.phone??null,email:l.email??null,googleEmail:l.googleEmail??null,approved:l.approvedAt!=null,specialization:l.specialization??null,bio:l.bio??null,position:l.position??null,photo:(l.profilePhotoUrl??l.photo??null),isPrincipal:!!l.isPrincipal,active:!!l.active,upcoming:Number(l.upcoming??(l.assignments?.length??0)),branchName:requestedBranchId?(branches.find((b:any)=>b.id===requestedBranchId)?.name_ar??null):(lawyerBranches.find((b:any)=>b.lawyer_id===l.id)?.branch_name??null)}))} locations={locations.map(l=>({...l,type:l.type as string}))} cases={cases.map(c=>({id:c.id,name:c.name,number:c.number,clientName:c.clientName,category_id:requestedBranchId?(c.category_id??null):(caseCategoryRows.find((x:any)=>x.id===c.id)?.category_id??null),events:(c.events??[]).map((e:any)=>({id:e.id,description:e.description,type:e.type,authorName:e.authorName,createdAt:new Date(e.createdAt).toISOString()}))}))} feedTasks={feed.items} categories={categories} activity={activity.map(a=>({id:a.id,action:a.action,summary:a.summary,createdAt:a.createdAt.toISOString()}))} notifications={notifications.map(n=>({id:n.id,type:n.type,title:n.title,body:n.body,link:n.link,readAt:n.readAt?.toISOString()??null,createdAt:n.createdAt.toISOString()}))}/></>);
}
