'use client';
import * as React from 'react';
import { useRouter } from 'next/navigation';
import { Loader2, Pencil } from 'lucide-react';
import { Button, Field, Input, Modal, Select, Textarea } from './ui';
import { toastSuccess, toastError } from './toasts';
export function LawyerProfileEditor({lawyerId,fullName,title,phone,email,specialization,bio,position}:{lawyerId:string;fullName:string;title:'DOCTOR'|'ADVOCATE';phone:string|null;email:string|null;specialization:string|null;bio:string|null;position:string|null}){
 const router=useRouter();const[open,setOpen]=React.useState(false);const[fullNameVal,setFullNameVal]=React.useState(fullName);const[titleVal,setTitleVal]=React.useState<'DOCTOR'|'ADVOCATE'>(title);const[phoneVal,setPhoneVal]=React.useState(phone??'');const[emailVal,setEmailVal]=React.useState(email??'');const[specializationVal,setSpecializationVal]=React.useState(specialization??'');const[bioVal,setBioVal]=React.useState(bio??'');const[positionVal,setPositionVal]=React.useState(position??'');const[busy,setBusy]=React.useState(false);
 const openEditor=()=>{setFullNameVal(fullName);setTitleVal(title);setPhoneVal(phone??'');setEmailVal(email??'');setSpecializationVal(specialization??'');setBioVal(bio??'');setPositionVal(position??'');setOpen(true)};
 const save=async()=>{setBusy(true);try{const payload={fullName:fullNameVal.trim(),title:titleVal,phone:phoneVal.trim()||null,email:emailVal.trim()||null,googleEmail:emailVal.trim()||null,specialization:specializationVal.trim()||null,bio:bioVal.trim()||null,position:positionVal.trim()||null};const res=await fetch(`/api/lawyers/${lawyerId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await res.json().catch(()=>({}));if(!res.ok)throw new Error(d.error||'تعذر إرسال التعديل');setOpen(false);toastSuccess('تم إرسال تعديل الملف للإدارة للموافقة ✓');router.refresh()}catch(e){toastError(e instanceof Error?e.message:'تعذر الاتصال بالخادم')}finally{setBusy(false)}};
 return <><button onClick={openEditor} className="flex items-center gap-1.5 border border-[#242424] px-3 py-1.5 text-[10px] tracking-[1.5px] uppercase text-[#242424] transition-colors hover:bg-[#242424] hover:text-[#F7F5F0]" style={{fontFamily:'IBM Plex Sans Arabic, sans-serif',letterSpacing:'1.5px'}}><Pencil size={11}/> تعديل صفحتي</button><Modal open={open} onClose={()=>{if(!busy)setOpen(false)}} title={`طلب تعديل الملف — ${fullName}`} wide footer={<div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setOpen(false)}>إلغاء</Button><Button onClick={()=>void save()} disabled={busy}>{busy&&<Loader2 size={14} className="animate-spin"/>}إرسال للإدارة</Button></div>}><div className="space-y-4"><p className="text-xs leading-6 text-navy-400">أي تعديل على بيانات الملف يُرسل أولاً للإدارة العليا لاعتماده.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="الصفة" required><Select value={titleVal} onChange={e=>setTitleVal(e.target.value as 'DOCTOR'|'ADVOCATE')}><option value="ADVOCATE">محامي</option><option value="DOCTOR">دكتور</option></Select></Field><Field label="الاسم الكامل" required><Input value={fullNameVal} onChange={e=>setFullNameVal(e.target.value)}/></Field><Field label="الهاتف"><Input value={phoneVal} onChange={e=>setPhoneVal(e.target.value)} dir="ltr"/></Field><Field label="البريد الإلكتروني"><Input value={emailVal} onChange={e=>setEmailVal(e.target.value)} type="email" dir="ltr"/></Field><Field label="المنصب"><Input value={positionVal} onChange={e=>setPositionVal(e.target.value)}/></Field><Field label="التخصص"><Input value={specializationVal} onChange={e=>setSpecializationVal(e.target.value)}/></Field></div><Field label="النبذة"><Textarea value={bioVal} onChange={e=>setBioVal(e.target.value)}/></Field></div></Modal></>;
}
