import { NextResponse } from 'next/server';
import { put } from '@vercel/blob';
import { prisma } from '@/lib/prisma';
import { user } from '@/lib/api';
import { isSeniorManagement, officeId } from '@/lib/office-workflow';

export async function GET(_req: Request,{params}:{params:Promise<{id:string}>}){const session=await user();if(!session)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});const{id}=await params;const files=await prisma.$queryRawUnsafe<any[]>(`SELECT "id","name","kind","mime_type","size_bytes","url","text_content","created_at" FROM "client_files" WHERE "client_id"=$1 AND "deleted_at" IS NULL ORDER BY "created_at" DESC`,id);return NextResponse.json({files});}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const session=await user();if(!session)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});const{id}=await params;const ct=req.headers.get('content-type')||'';let name='',kind='note',mime:string|null=null,size=0,url:string|null=null,text:string|null=null;
 if(ct.includes('multipart/form-data')){const form=await req.formData();const file=form.get('file');name=String(form.get('name')|| (file instanceof File?file.name:'ملف جديد'));text=String(form.get('text')||'')||null;if(file instanceof File){size=file.size;mime=file.type||null;kind=mime?.startsWith('image/')?'image':(mime==='application/pdf'?'pdf':(mime?.includes('word')?'word':'file'));if(!process.env.BLOB_READ_WRITE_TOKEN)return NextResponse.json({error:'تخزين الملفات غير مضبوط على Vercel (BLOB_READ_WRITE_TOKEN)'},{status:503});const blob=await put(`clients/${id}/${Date.now()}-${file.name.replace(/[^\w.\-\u0600-\u06ff ]/g,'_')}`,file,{access:'public'});url=blob.url;}}
 else {const body=await req.json();name=String(body.name||'ملاحظة');kind=String(body.kind||'note');url=body.url?String(body.url):null;text=body.text?String(body.text):null;mime=body.mimeType?String(body.mimeType):null;size=Number(body.size||0);}
 if(!name.trim())return NextResponse.json({error:'اسم الملف مطلوب'},{status:400});const fileId=officeId('clientfile');await prisma.$executeRawUnsafe(`INSERT INTO "client_files" ("id","client_id","name","kind","mime_type","size_bytes","url","text_content","created_by_user_id","created_by_lawyer_id") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,fileId,id,name.trim(),kind,mime,size,url,text,session.role==='admin'?session.userId:null,session.role==='lawyer'?session.lawyerId:null);return NextResponse.json({ok:true,id:fileId,url});}
